server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: jodosSpringboot
    password: jodos2006
    url: jdbc:mysql://localhost:3306/registration

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

security:
  filter-chain-bean: securityFilterChain
